version: "2.1"

services:
  pdf-service:
    container_name: pdf_service:latest
    image: pdf_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:8000
    environment:
      PDF_SERVICE_PORT: 8000

  yarn:
    image: buildkite/puppeteer:10.0.0
    working_dir: /app
    volumes:
      - "./:/app"
      - "~/.yarn-cache/v6/supervision:/usr/local/share/.cache/yarn/v6"
    entrypoint: ['yarn']
