version: "2.1"

services:
  pdf-service:
    container_name: pdf-service
    image: pdf-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3004:8000
    environment:
      PDF_SERVICE_PORT: 8000

  pdf-service-test:
    container_name: pdf-service-test
    image: pdf-service:test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    working_dir: /app
    volumes:
      - "./coverage:/app/coverage"
      - "./test-results:/app/test-results"
      - "~/.yarn-cache/v6/pdf-service:/usr/local/share/.cache/yarn/v6"
  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.trivy-cache:/root/.cache
      - ./test-results:/test-results
      - ./.trivyignore:/.trivyignore
