on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  test:
    name: Test PDF Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Dependencies from Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run Javascript Linting
        run: |
          make lint-test

      - name: Run Unit Tests & Generate Coverage Report
        run: |
          mkdir -p /home/runner/project/build/service-pdf
          make unit-test-coverage

      - name: Run SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload Junit
        uses: actions/upload-artifact@v3
        with:
          name: junit
          path: |
            test-results/junit

      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: /home/runner/project/build/service-pdf
